export const CATEGORY = 'CATEGORY'
export const CATEGORYTABLIST = 'CATEGORYTABLIST'
export const GOODSDETAILS = 'GOODSDETAILS'
export const USERNAME = 'USERNAME'
export const ADDRESSINFO = 'ADDRESSINFO'
export const BROWSE = 'BROWSE'
export const SHOPORDERLIST = 'SHOPORDERLIST'
export const TEMPORARYADDRESS = 'TEMPORARYADDRESS'
export const CITY = 'CITY'
export const ACTIVE = 'ACTIVE'
export const SEARCHHISTORYLIST = 'SEARCHHISTORYLIST'



